### ISSUE TITLE
Peer to peer code review-6/6/23

### ISSUE THREAD

**Issue by hassanShakur** [kerlos-bahaa/Awesome-books#10]
Awesome work on the project. The design is very similar to the provided one and the functionality works perfectly ✅. You might only consider one improvement in your `index.js` - that is ensuring you follow the `DRY` principle when writing your code to prevent repetition. Other than that, good work.

**Comment by rmiyoyo** [comment]
# Issues Noticed
Hi @kerlos-bahaa, great work with your project so far! 💯 
- [x] You have done a good job keeping the project elegant and simple. 

However, I noticed a few minor issues with the readme:
- [x] Kindly consider deploying your project to Github Pages and adding the deployment link to README 👍 
- [x] In your [setup](https://github.com/kerlos-bahaa/Awesome-books#setup) section, you could consider removing the link from the brackets and giving the instructions in list format to give more clarity to an end user. 🙏

**Comment by kerlos-bahaa** [comment]
thank you so much for the feedback I will take that to mind

**Comment by Samuelwanza** [comment]
This is great work so far. Kindly consider making the cursor a pointer, when you hover the nav links

**Comment by hassanShakur** [comment]
Issue fixed.
